main.py
from flask import Flask,render_template, redirect, request, url_for
from flask_login import LoginManager,current_user, login_required,\
    logout_user, login_user

from user import User
from loginform import LoginForm
from usermanager import create_user, get_user

from flask_bootstrap import Bootstrap


app = Flask(__name__)
app.debug = True
bootstrap = Bootstrap(app)
app.config['BOOTSTRAP_SERVE_LOCAL'] = True

# Set the secret key to some random bytes. Keep this really secret!
app.secret_key = b'_5#y2L"F4Q8z\n\xec]/'

login_manager = LoginManager()
login_manager.init_app(app)
login_manager.login_view = 'login' # view endpoint 


@login_manager.user_loader # define function for getting user
def load_user(user_id):
    return User.get(user_id)


@app.route('/')
@login_required
def index():
    return render_template('index.html',username=current_user.username)


@app.route('/login/', methods=('GET','POST'))
def login():
    form = LoginForm()
    emsg = None
    if form.validate_on_submit():
        user_name = form.username.data
        password = form.password.data
        user = get_user(user_name) # get user data from db

        if user is None:
            emsg = 'error password or username'
        else:
            if user.verify_password(password):
                login_user(user, remember=True) # create session
                return redirect(request.args.get('next') or url_for('index'))
            else:
                emsg = 'username or password wrong'

    return render_template('login.html', form=form, emsg=emsg)


@app.route('/register/', methods=('GET','POST'))
def register():
    form = LoginForm()
    emsg = None
    if form.validate_on_submit():
        user_name = form.username.data
        password = form.password.data
        user_info = get_user(user_name) # get user data from db

        if user_info is not None:
            emsg = 'username exist'
        else:
            create_user(user_name=user_name, password=password)
            return redirect(url_for('index'))
    return render_template('register.html', form=form, emsg=emsg)


@app.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('login'))


# 登出视图不需要模板，直接跳转到登录页，实际项目中可以增加一个登出页，展示些有趣的东西
if __name__ == '__main__':
    app.run()

myflask/blueprints/action.py
from flask import Blueprint

action = Blueprint("action", __name__, url_prefix="/action")


@action.route('/login/', methods=('GET','POST'))
def login():
    form = LoginForm()
    emsg = None
    if form.validate_on_submit():
        user_name = form.username.data
        password = form.password.data
        user = get_user(user_name) # get user data from db

        if user is None:
            emsg = 'error password or username'
        else:
            if user.verify_password(password):
                login_user(user, remember=True) # create session
                return redirect(request.args.get('next') or url_for('index'))
            else:
                emsg = 'username or password wrong'

    return render_template('login.html', form=form, emsg=emsg)


@app.route('/register/', methods=('GET','POST'))
def register():
    form = LoginForm()
    emsg = None
    if form.validate_on_submit():
        user_name = form.username.data
        password = form.password.data
        user_info = get_user(user_name) # get user data from db

        if user_info is not None:
            emsg = 'username exist'
        else:
            create_user(user_name=user_name, password=password)
            return redirect(url_for('index'))
    return render_template('register.html', form=form, emsg=emsg)

myflask/blueprints/home.py
from flask import Blueprint, render_template
from flask_login import current_user, login_required

home = Blueprint("home", __name__, url_prefix="/home")

@home.route('/')
@login_required
def index():
    print('index')
    return render_template('index.html',username=current_user.username)

myflask/blueprints/index.py
from flask import Blueprint, render_template

index = Blueprint("/", __name__, template_folder="templates")


@index.route('/')
def main():
    return render_template('index.html')

templates/base.html
<!-- 引入导航模块的宏 render_nav_item -->
{% from 'bootstrap/nav.html' import render_nav_item %}
<!-- 下面是正常的 Bootstrap 页面代码，看起来很复杂，不过可以从官网上拷贝 -->

<!DOCTYPE html>
<html lang="cn">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>{% block title %} Flask Bootstrap {% endblock %}</title> <!-- 定义标题块 -->
        <link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}">
        {{ bootstrap.load_css() }}  <!-- 动态加载 Bootstrap 样式 -->
    </head>
    <body>
    <main class="container">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="navbar-header">
                <a class="navbar-brand" href="#">Python</a>
            </div>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <!-- 利用宏 render_nav_item 创建菜单 -->
                    {{ render_nav_item('home.index', '首页', use_li=True) }}
                    {{ render_nav_item('action.login', '登录', use_li=True) }}
                    {{ render_nav_item('action.register', '注册', use_li=True) }}
                    {{ render_nav_item('blog.index','Blog', use_li=True) }}
                </ul>
            </div>
        </nav>
        {% block content %}  <!-- 定义内容块 -->
        <h1> Hello Flask Bootstrap! </h1>
        {% endblock %}
        <footer class="text-center">
            {% block footer %} <!-- 定义页脚块 -->
                <small> &copy; 2020 <a href="http://www.beian.miit.gov.cn" title="粤ICP备18006582号">粤ICP备18006582号</a>
                </small>
            {% endblock %}
        </footer>
    </main>

    <!-- 动态加载 Bootstrap js 脚本 -->
    {{ bootstrap.load_js() }}
    <!-- 腾讯mta -->
    <script>
                var _mtac = {};
                (function() {
                    var mta = document.createElement("script");
                    mta.src = "//pingjs.qq.com/h5/stats.js?v2.0.4";
                    mta.setAttribute("name", "MTAH5");
                    mta.setAttribute("sid", "500727921");
                    var s = document.getElementsByTagName("script")[0];
                    s.parentNode.insertBefore(mta, s);
                })();
    </script>
    </body>
</html>

templates/blog.html
{% extends "base.html" %} <!-- 继承基础模板 -->

{% block content %} <!-- 替换页面内容 -->
<h1> {{ title }} </h1>

<div id="container" style="width:100%; height:400px;"></div>
<body>{{ content }} </body>
{% endblock %}

templates/blog/blog.html
{% extends 'base.html' %}

{% block header %}
  <h1>{% block title %}Posts{% endblock %}</h1>
{% endblock %}

{% block content %}
  {% if username %}
    <a class="action" href="{{ url_for('blog.create') }}">New</a>
  {% endif %}

  {% for post in posts %}
    <article class="post">
      <header>
        <div>
          <h1>{{ post['title'] }}</h1>
        </div>
      </header>
      <p class="body">{{ post['content'] }}</p>
    </article>
    {% if not loop.last %}
      <hr>
    {% endif %}
  {% endfor %}
{% endblock %}

templates/blog/blog_content.html
{% extends "base.html" %} <!-- 继承基础模板 -->

{% block content %} <!-- 替换页面内容 -->
<h1> {{ title }} </h1>

<div id="container" style="width:100%; height:400px;"></div>
<body>{{ content }} </body>
{% endblock %}

templates/blog/create.html
{% extends 'base.html' %}

{% block header %}
  <h1>{% block title %}New Post{% endblock %}</h1>
{% endblock %}

{% block content %}
  <form method="post">
    <label for="title">Title</label>
    <input name="title" id="title" value="{{ request.form['title'] }}" required>
    <label for="body">Body</label>
    <textarea name="body" id="body">{{ request.form['body'] }}</textarea>
    <input type="submit" value="Save">
  </form>
{% endblock %}

templates/home.html
{% extends "base.html" %} <!-- 继承基础模板 -->

{% block content %} <!-- 替换页面内容 -->

<h1>Welcome {{ username }} ! </h1>
<script src="https://code.highcharts.com/highcharts.js"></script>

<div id="container" style="width:100%; height:400px;"></div>
<script>

	document.addEventListener('DOMContentLoaded', function () {
        var myChart = Highcharts.chart('container', {
            chart: {
                type: 'bar'
            },
            title: {
                text: 'Fruit Consumption'
            },
            xAxis: {
                categories: ['Apples', 'Bananas', 'Oranges']
            },
            yAxis: {
                title: {
                    text: 'Fruit eaten'
                }
            },
            series: [{
                name: 'Jane',
                data: [1, 0, 4]
            }, {
                name: 'John',
                data: [5, 7, 3]
            }]
        });
    });

</script>
<a href="{{ url_for('action.logout') }}">Logout</a>
{% endblock %}

templates/index.html
<!DOCTYPE html>
<html lang="sc">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>又是元气满满的一天</title>
    <link rel="stylesheet" href="static/css/style.css">
    <!-- fonts-->
    <link
            href="static/font/css?family=Encode+Sans+Condensed:200,400,500,600,700,900"
          rel="stylesheet">

</head>
<body>
<h1 class="text-intro">En ce moment chez BeCode Charleroi...</h1>
<div class="logo"><img src="static/images/becode.png" alt=""></div>

<section class="crawl">
    <div>
        <h2>Hey ho fieu ! Un petit truc à savoir ;)</h2>
        <blockquote>“Oser et faire. Il est plus facile de demander le pardon
            après, que la permission avant.”
        </blockquote>
        <p>L’homme n’aurait jamais pu marcher sur la Lune sans l’aide d’une
            femme, en l’occurrence Margaret Hamilton qui a corrigé à la main les
            programmes de la mission Apollo 11.
        </p>
        <p>Elle avait ainsi anticipé certaines pannes des composants
            électroniques et fait en sorte que la commande pour l’alunissage
            reste fonctionnelle. C’est à elle et son travail que l’on doit le
            succès de la mission.
        </p>
        <p>A l’époque, il faut savoir que la partie développement logiciel était
            souvent réservée aux femmes car jugée moins importante.
        </p>
        <blockquote>"Un petit extrait de Star Wars: The Last Jedi"</blockquote>
        <iframe width="800px" height="450px"
                src="https://live.bilibili.com/3963033"
                frameborder="0" allow="autoplay; encrypted-media"
                allowfullscreen></iframe>

        <audio controls="controls" autoplay="autoplay">
        <source src="http://m10.music.126.net/20200827210234/63d67973b2696295cb3230cc94e22c4f/ymusic/ac16/5b38/006c/c0f3c595da90066b2e46dc89c214d39d.mp3
        " type="audio/mpeg" />
        Your browser does not support the audio element.
        </audio>
        <p>Tu trouve ça cool ? va voir ici</p>
        <a href="https://energygreek.github.io">Greek Github</a>
    </div>

</section>
<div class="btn"><a href="https://www.beautyflying.cn/home">欢迎光临</a></div>
</body>
</html>

templates/login.html
{% extends "base.html"  %}

{% block content  %}

<h1> Login </h1>

{% macro render_field(field) %}
  <dt>{{ field.label }}:
  <dd>{{ field(**kwargs)|safe }}
  {% if field.errors %}
    <ul class=errors>
      {% for error in field.errors %}
        <li>{{ error }}</li>
      {% endfor %}
    </ul>
  {% endif %}
{% endmacro %}


<form method="POST">
  {{ form.csrf_token }}
  {{ render_field(form.username) }}
  {{ render_field(form.password) }}
  {% if emsg %}
    <h3> {{ emsg }} </h3>
  {% endif %}
  <input type="submit" value="Login">
</form>

{% endblock %}

templates/register.html
{% extends "base.html"  %}

{% block content  %}

<h1>  Sign Up </h1>

{% macro render_field(field) %}
  <dt>{{ field.label }}:
  <dd>{{ field(**kwargs)|safe }}
  {% if field.errors %}
    <ul class=errors>
      {% for error in field.errors %}
        <li>{{ error }}</li>
      {% endfor %}
    </ul>
  {% endif %}
{% endmacro %}


<form method="POST">
  {{ form.csrf_token }}
  {{ render_field(form.username) }}
  {{ render_field(form.password) }}
  {% if emsg %}
    <h3> {{ emsg }} </h3>
  {% endif %}
  <input type="submit" value="Register">
</form>

{% endblock %}